# Generated by Django 5.1 on 2024-08-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="cars_image",
            field=models.ImageField(blank=True, null=True, upload_to="cars_images/"),
        ),
    ]
